align_modal <- modalDialog(
  size = "m",
  title = textOutput(outputId = "align_modal_title"),
  easyClose = TRUE,
  fluidRow(column(width = 12,
                  textInput("dataset_name", "Choose a name for this dataset (optional)",
                            placeholder = ""
                  ))),
  div(tags$hr()),
  fluidRow(
    column(width = 4, style = "margin-top:0px;margin-left:0px;",
           actionButton(inputId = "begin_processing",
                        label = "Begin PACER ...",
                        width = "100%")),
    column(width = 4, offset = 4, style = "margin-top:0px;",
           actionButton(inputId = "close_modal",
                        label = "Cancel",
                        width = "100%"))),
  footer = NULL)

adapter_modal <- modalDialog(size = "l",
                             title = "Adapters",
                             easyClose = FALSE,
                             #tags$div(class = "modal-adapter",
                             fluidRow(column(width = 12, tableOutput("adapter_table"))),
                             div(tags$hr(style = "margin-top:0px;")),
                             fluidRow(
                               column(width = 4, style = "margin-top:0px; margin:0px;",
                                      textInput(inputId = "add_adapter_sequence_input",
                                                label = "Adapter",
                                                width = "100%")),
                               column(width = 4, style = "margin-top:0px; margin:0px;",
                                      textInput(inputId = "add_adapter_description_input",
                                                label = "Description",
                                                width = "100%")),
                               column(width = 2, style = "margin-top:25px",
                                      actionButton(inputId = "add_adapter",
                                                   label = "Add Adapter",
                                                   width = "100%"))),
                             div(tags$hr(style = "margin-top:0px;")),
                             fluidRow(
                               column(width = 6, style = "margin-top:0px",
                                      selectInput(inputId = "adapter_index",
                                                  label = "Select adapter to remove",
                                                  multiple = FALSE,
                                                  choices = NULL,
                                                  width = "100%"
                                                  )),
                               column(width = 2, style = "margin-top:24px",
                                      actionButton(inputId = "remove_adapter",
                                                   label = "Remove Adapter",
                                                   width = "100%"))
                             ),
                             div(tags$hr()),
                             fluidRow(
                               column(width = 2, style = "margin-top:0px;margin-left:0px;",
                                      actionButton(inputId = "save_adapters",
                                                   label = "Save Changes",
                                                   width = "100%")),
                               column(width = 1,
                                      style = "margin-top:8px;text-align:left;",
                                      textOutput(outputId = "adapter_changes_saved")),
                               #column(width = 7, style = "margin-top:0px"),
                               column(width = 2, offset = 7, style = "margin-top:0px;",
                                      actionButton(inputId = "close_modal",
                                                   label = "Exit",
                                                   width = "100%"))),
                             footer = NULL)

genomes_modal <- modalDialog(size = "l",
                             title = "Genomes",
                             easyClose = FALSE,
                             fluidRow(column(width = 12,
                                             tableOutput(outputId = "genome_table"))),
                             fluidRow(
                               column(width = 6,
                                      style = "margin-top:0px;",
                                      selectInput(inputId = "genome_index",
                                                  label = "Select genome",
                                                  multiple = FALSE,
                                                  choices = "",
                                                  width = "100%")),
                               column(width = 2, style = "margin-top:23px;",
                                      (actionButton(inputId = "load_genome",
                                                            label = "Load Genome",
                                                            width = "100%"))),
                               column(width = 2, style = "margin-top:23px;",
                                      (actionButton(inputId = "view_genome",
                                                            label = "View Genome Info",
                                                            width = "100%"))),
                               column(width = 2, style = "margin-top:23px;",
                                      (actionButton(inputId = "remove_genome",
                                                            label = "Remove Genome",
                                                            width = "100%")))),
                             #div(tags$hr()),
                             hidden(
                               div(id = "genome_details", style = "border:5;border-color:grey;",
                                   wellPanel(
                                     fluidRow(
                                       column(width = 2, style = "margin-bottom:6px",
                                              actionButton(inputId = "get_intervals",
                                                           label = "Get Intervals")),
                                       column(width = 2, style = "margin-bottom:6px;margin-top:9px;",
                                              "ENSEMBL Intervals"),
                                       column(width = 6, style = "margin-bottom:6px;margin-top:9px;",
                                              htmlOutput(outputId = "genome_interval_status"))
                                     ),
                                     fluidRow(
                                       column(width = 2, style = "margin-bottom:6px",
                                              shinyFilesButton(id = "genome_fasta_finder",
                                                               title = "Find genome FASTA",
                                                               label = "Find file ...",
                                                               multiple = FALSE)),
                                       column(width = 2, style = "margin-bottom:6px;margin-top:9px;",
                                              "Genome FASTA"),
                                       column(width = 6, style = "margin-bottom:6px;margin-top:9px;",
                                              htmlOutput(outputId = "genome_fasta_location"))

                                     ),
                                     fluidRow(
                                       column(width = 2, style = "margin-bottom:6px",
                                              shinyDirButton(id = "genome_index_finder",
                                                             title = "Find genome index directory",
                                                             label = "Find directory ...")),
                                       column(width = 2, style = "margin-bottom:6px;margin-top:9px;",
                                              "Bowtie Index"),
                                       column(width = 6, style = "margin-bottom:6px;margin-top:9px;",
                                              htmlOutput(outputId = "genome_index_location"))

                                     ),
                                     fluidRow(
                                       column(width = 2, style = "margin-bottom:6px",
                                              shinyFilesButton(id = "gene_list_finder",
                                                               title = "Find gene lists",
                                                               label = "Find gene list(s) ...",
                                                               multiple = FALSE)),
                                       column(width = 2, style = "margin-bottom:6px;margin-top:9px;",
                                              "Gene lists"),
                                       column(width = 6, style = "margin-bottom:6px;margin-top:2px;",
                                              selectInput(inputId = "gene_list_status",
                                                          label = NULL,
                                                          choices = "",
                                                          multiple = FALSE,
                                                          selectize = TRUE,
                                                          width = "100%")),
                                       column(width = 2, style = "margin-bottom:6px;margin-top:0px;",
                                              actionButton(inputId = "remove_gene_list", label = "Remove list"))
                                     )
                                   )),
                               div(tags$hr())),
                             div(tags$hr()),
                             fluidRow(
                               column(width = 6, style = "margin-top:0px",
                                      selectInput(inputId = "ensembl_genome_index",
                                                  selectize=TRUE,
                                                  width = "100%",
                                                  label = "ENSEMBL Genomes",
                                                  multiple = FALSE, choices = "")),
                               column(width = 3, style = "margin-top:23px",
                                      actionButton(inputId = "get_ensembl_genomes",
                                                   label = "Get ENSEMBL genomes",
                                                   width = "100%")),
                               column(width = 2, style = "margin-top:24px",
                                      disabled(
                                        actionButton(inputId = "add_genome",
                                                     label = "Add genome",
                                                     width = "100%")))),
                             div(tags$hr()),
                             fluidRow(
                               column(width = 2, style = "margin-top:0px;margin-left:0px;",
                                      actionButton(inputId = "save_genomes",
                                                   label = "Save Changes",
                                                   width = "100%")),
                               column(width = 1,
                                      style = "margin-top:8px;text-align:left;",
                                      textOutput(outputId = "genome_changes_saved")),
                               #column(width = 7, style = "margin-top:0px"),
                               column(width = 2, offset = 7, style = "margin-top:0px;",
                                      actionButton(inputId = "close_modal",
                                                   label = "Exit",
                                                   width = "100%"))),
                             footer = NULL)
